version: '3'

services:
    proxy:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: gustavenrique/proxy
        container_name: gustavenrique/fib-proxy
        restart: always
        ports:
            - 3000:80
        depends_on:
            - fib-api
            - fib-ui

    postgres:
        image: 'postgres:16-bookworm'
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=j3iy8.32HD1u@@w#

    redis:
        image: 'redis:7.2-bookworm'
        container_name: redis
        restart: always

    fib-api:
        build:
            context: ./api
            dockerfile: Dockerfile
        image: gustavenrique/fib-api
        container_name: fib-api
        restart: always
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=j3iy8.32HD1u@@w#
            - POSTGRES_DATABASE=postgres
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - PORT=5000
        depends_on:
            - postgres
            - redis

    fib-worker:
        build:
            context: ./worker
            dockerfile: Dockerfile
        image: gustavenrique/fib-worker
        container_name: fib-worker
        restart: unless-stopped
        environment:
            - REDIS_CONNECTION=redis://redis:6379
        depends_on:
            - redis

    fib-ui:
        build:
            context: ./ui
            dockerfile: Dockerfile
        image: gustavenrique/fib-ui
        container_name: fib-ui
        restart: always
        environment:
            - WDS_SOCKET_PORT=3000
