version: '3'

services:
  router:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3000:80
    depends_on:
      - fib-api
      - fib-ui

  postgres:
    image: 'postgres:16-bookworm'
    restart: always
    environment:
      - POSTGRES_PASSWORD=dev_password#

  redis:
    image: 'redis:7.2-bookworm'
    restart: always

  fib-api:
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    image: gustavenrique/fib-api:dev
    restart: always
    volumes:
      - /app/node_modules
      - ./api:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev_password#
      - POSTGRES_DATABASE=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - PORT=5000
    depends_on:
      - postgres
      - redis

  fib-worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    image: gustavenrique/fib-worker:dev
    restart: unless-stopped
    volumes: 
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_CONNECTION=redis://redis:6379
    depends_on:
      - redis
      
  fib-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    image: gustavenrique/fib-ui:dev
    restart: always
    volumes: 
      - /app/node_modules
      - ./ui:/app
    environment:
      - WDS_SOCKET_PORT=3000